# Generated by Django 5.2 on 2025-07-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('tipo_base', models.CharField(choices=[('espresso', 'Espresso'), ('americano', 'Americano'), ('latte', 'Latte')], max_length=20)),
                ('ingredientes', models.JSONField(default=list)),
                ('tamanio', models.CharField(choices=[('pequenio', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
