# Generated by Django 5.2 on 2025-07-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='ingredientes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
