# Generated by Django 5.2 on 2025-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0002_alter_pedidocafe_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='ingredientes',
            field=models.JSONField(default=list),
        ),
    ]
