# Generated by Django 5.2 on 2025-07-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0003_alter_pedidocafe_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='tamanio',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10),
        ),
    ]
